
---
- name: add php repository
  apt_repository:
    repo: ppa:ondrej/php

- name: add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

- name: add nodejs GPG key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: add nodejs repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x focal main"
    filename: nodesource

- name: add yarn GPG key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: add yarn repository
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    filename: yarn

- name: add mariadb key
  apt_key:
    url: https://mariadb.org/mariadb_release_signing_key.asc

- name: add mariadb repository
  apt_repository:
    repo: deb [arch=amd64,arm64,ppc64el] http://sfo1.mirrors.digitalocean.com/mariadb/repo/10.6/ubuntu focal main
    filename: mariadb
