---
- name: Install apt packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - git-crypt
      - jq
      - unzip
      - zip

- name: Add current user to docker group
  ansible.builtin.user:
    name: "{{ ansible_env['USER'] }}"
    groups: docker
    append: yes
