---
- name: install apt packages
  ansible.builtin.apt:
    name:
      - apache2
      - docker-ce
      - git-crypt
      - mariadb-server
      - nodejs
      - php7.4-bcmath
      - php7.4-cli
      - php7.4-curl
      - php7.4-dev
      - php7.4-fpm
      - php7.4-gd
      - php7.4-igbinary
      - php7.4-imap
      - php7.4-intl
      - php7.4-ldap
      - php7.4-mbstring
      - php7.4-memcached
      - php7.4-msgpack
      - php7.4-mysql
      - php7.4-pgsql
      - php7.4-readline
      - php7.4-redis
      - php7.4-soap
      - php7.4-sqlite3
      - php7.4-tidy
      - php7.4-xdebug
      - php7.4-xml
      - php7.4-zip
      - php8.0-bcmath
      - php8.0-cli
      - php8.0-curl
      - php8.0-dev
      - php8.0-fpm
      - php8.0-gd
      - php8.0-igbinary
      - php8.0-imap
      - php8.0-intl
      - php8.0-ldap
      - php8.0-mbstring
      - php8.0-memcached
      - php8.0-msgpack
      - php8.0-mysql
      - php8.0-pgsql
      - php8.0-readline
      - php8.0-redis
      - php8.0-soap
      - php8.0-sqlite3
      - php8.0-tidy
      - php8.0-xdebug
      - php8.0-xml
      - php8.0-zip
      - postfix
      - yarn
    force_apt_get: yes
    update_cache: yes

- name: add current user to docker group
  ansible.builtin.user:
    name: "{{ ansible_env['USER'] }}"
    groups: docker
    append: yes
