---
- name: Change iptables to legacy (for docker network)
  community.general.alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy

- name: Install apt packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-compose-plugin
      - git-crypt
      - jq
      - unzip
      - zip

- name: Add current user to docker group
  ansible.builtin.user:
    name: "{{ ansible_env['USER'] }}"
    groups: docker
    append: yes
