---
- name: Import task add_repositories
  ansible.builtin.import_tasks: add_repositories.yml

- name: Import task install_packages
  ansible.builtin.import_tasks: install_packages.yml
  tags: install
