---
- name: import task add_repositories
  import_tasks: add_repositories.yml

- name: import task install_packages
  import_tasks: install_packages.yml
  tags: install

- name: enable proxy_fcgi, ssl module
  community.general.apache2_module:
    name: '{{ item }}'
  loop:
    - proxy_fcgi
    - ssl

- name: copy apache2/sites-available/000-wsl.conf
  copy:
    src: 000-wsl.conf
    dest: /etc/apache2/sites-available

- name: check apache 000-default.conf
  stat:
    path: /etc/apache2/sites-enabled/000-default.conf
  register: apache_default_conf

- name: disable 000-default.conf
  command: a2dissite 000-default.conf
  when: apache_default_conf.stat.exists

- name: check apache 000-wsl.conf
  stat:
    path: /etc/apache2/sites-enabled/000-wsl.conf
  register: apache_wsl_conf

- name: enable apache 000-wsl.conf
  command: a2ensite 000-wsl
  when: not apache_wsl_conf.stat.exists

- name: changed php-fpm user
  community.general.ini_file:
    path: '{{ item }}'
    section: www
    option: user
    value: "{{ ansible_env['USER'] }}"
  loop:
    - /etc/php/7.4/fpm/pool.d/www.conf
    - /etc/php/8.0/fpm/pool.d/www.conf
